#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

./makeMesh
#decomposePar
#mpirun -np 4 pimpleFoam -parallel 
#runApplication pimpleFoam &

rm -rf processor* log.decomposePar
runApplication decomposePar
runParallel renumberMesh -overwrite
runParallel -append pimpleFoam
runApplication -append reconstructPar

#------------------------------------------------------------------------------
