#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

./Allclean
./revalue
rm 0 -r
cp 0_org 0 -r
#cp constant/momentumTransport.kEpsilon constant/momentumTransport

runApplication blockMesh
runApplication surfaceFeatures
#snappyHexMesh -overwrite
runApplication decomposePar -copyZero
runParallel snappyHexMesh -overwrite 
runApplication reconstructParMesh -constant -mergeTol 1e-6
touch t.foam


